### ISSUE TITLE
Hard to use exclude_pattern to enable specific urls

### ISSUE THREAD

**Issue by umpirsky** [scheb/two-factor-bundle#101]
The use case: I want to include 2FA for `/admin/*` and `/dev/*` urls only.

Since [RequestListener.php#L71](https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/EventListener/RequestListener.php#L71) wraps regex with `#`, it makes it hard (impossible with my knowledge of regex :)) to [reverse preg_match](https://stackoverflow.com/questions/5704061/php-reverse-preg-match).

Without them it's easy:

```
php > var_dump(preg_match('/^(?:(?!(admin|dev)).)*$/i', '/admin/foo'));
int(0)
php > var_dump(preg_match('/^(?:(?!(admin|dev)).)*$/i', '/adm2in/foo'));
int(1)
```

**Comment by scheb** [comment]
Please don't do that. The exclude_pattern option is really not meant to apply 2fa only to specific pages (like an admin area). It was actually only meant to by-pass routes, which are delivering non-critical content like assets. If 2fa is required for a user, there should actually be no other way than completing the 2fa step. This is essential for the way the 2fa works in the bundle, because otherwise someone who has stolen credentials could already browse parts of the page as a fully authenticated user.

**Comment by umpirsky** [comment]
@scheb But what if I just want to read some articles on the site from my phone and I'm logged in, should I be prompted with 2FA? No, I want to be prompted only if this page actually requires some security, not for public pages.

**Comment by scheb** [comment]
If it's only about reading some public pages, then why would you log-in in the first place? ;)

Sorry, but I don't agree with that view. Two-factor-authentication - as the name says - is an *authentication* method, that means it there to verify your identity and protect your account from identity theft. Therefore it is essential to deny access to an account until all challenges have been sucessfully completed. If you want to have an area in your application which requires special security, you should think about defining another secured area in the security.yaml.

But back to topic again: I don't see how the pre-definied delimiter keeps your regex from working. The only thing you cannot do is adding the `i` modifier, but aren't routes case-sensitive anyways?

**Comment by umpirsky** [comment]
> If it's only about reading some public pages, then why would you log-in in the first place? ;)

@scheb Following use case: you are logged in with remember me cookie, but don't want to remember 2FA code on your phone, tomorrow, you want to read some public page, you are logged back in with remember me cookie, but prompted to enter 2FA code - pretty annoying. :)
I don't think any changes to `security.yml` can prevent this.

> But back to topic again: I don't see how the pre-definied delimiter keeps your regex from working. The only thing you cannot do is adding the i modifier, but aren't routes case-sensitive anyways?

This is what I ended up with:

```php
use Scheb\TwoFactorBundle\Security\TwoFactor\EventListener\RequestListener as BaseRequestListener;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;

class RequestListener extends BaseRequestListener
{
    public function onCoreRequest(GetResponseEvent $event)
    {
        $request = $event->getRequest();

        if (!preg_match('/^(\/(admin|foo|bar))/', $request->getPathInfo())) {
            return;
        }

        parent::onCoreRequest($event);
    }
}
```

It works pretty nice, but it would be better if this is achievable without overriding vendors code.

If I want to reuse above regex with current code, I'd need to find a way to negate it, and I cannot with `#` delimeters: `preg_match('#'.$this->excludePattern.'#', $request->getPathInfo())`.
Why do we have `#` here? I don't know what it stands for, but it makes it hard to negate. If you know how to overcome this limitation, please share, maybe it will be useful for someone in the future too.

Thanks.

**Comment by scheb** [comment]
`#` is the delimiter. I use it because it is rarely needed when doing regular expressions on paths, while the standard `/` is needed quite often. So you can safe yourself the hassle with escaping `/` in the regular expression since it's no longer a reserved character - which makes the regex also more readable in my opinion.

I don't get it, why you cannot use the `^(?:(?!(admin|dev)).)*$` with a `#` delimiter. It shouldn't matter. Only thing that's different is that you don't need to escape the `/` characters. Or do I miss something here and specific regex features only work with specific delimiters?

**Comment by umpirsky** [comment]
@scheb Try to wrap regexes from the issue description with `#` and you will see the result. Not same as with `/`.

**Comment by umpirsky** [comment]
@scheb Imagine following scenario:

- User logged in into website from several different devices.
- He activates 2FA, logs in with 2FA - everything is fine.
- He tries to visit public URL from some of devices that he didn't confirm 2FA yet, and got 2FA form.

The point is - it's not user friendly to prompt user for 2FA just to visit public url.

I just setup 2FA for GitHub to see how they do it. It's quite elegant actually - you are not logged in untill you enter 2FA code, so you can browse public pages easily.

**Comment by scheb** [comment]
We don't need to discuss the scenario, I totally understand what you want to achieve - I personally still think it's a bad idea to weaken 2fa like that. But in the end feel free to implement it in your application how you like it.

Since you mentioned it, one thing to note: If you are logged in with 2fa on several devices and you activate it on one device, you will not be shown a 2fa form on any device that you're already logged in. It will only trigger when you're logged out and log-in again.

And regarding the regex, still don't see the issue:

```php
var_dump(preg_match('#^(?:(?!(admin|dev)).)*$#', '/admin/foo'));
int(0)
var_dump(preg_match('#^(?:(?!(admin|dev)).)*$#', '/adm2in/foo'));
int(1)
```

**Comment by umpirsky** [comment]
> We don't need to discuss the scenario, I totally understand what you want to achieve - I personally still think it's a bad idea to weaken 2fa like that. But in the end feel free to implement it in your application how you like it

Sure, thanks for the answer!

> It will only trigger when you're logged out and log-in again.

This is remember me scenario, right? When you are re-authenticated using remember me cookie.

Yes, regex worked, I must have missed something, Thanks!

**Comment by scheb** [comment]
>> It will only trigger when you're logged out and log-in again.

> This is remember me scenario, right? When you are re-authenticated using remember me cookie.

For the remember-me scenario it doesn't trigger, only for the username+password scenario. Unless you [configure the RememberMeToken](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md) in `security_tokens` to trigger 2fa.

**Comment by umpirsky** [comment]
> For the remember-me scenario it doesn't trigger, only for the username+password scenario. Unless you configure the RememberMeToken in security_tokens to trigger 2f

I did!
