### ISSUE TITLE
Support Google Authenticator digit lengths != 6

### ISSUE THREAD

**Issue by lstrojny** [scheb/two-factor-bundle#118]
The default number of digits for Google Authenticator is 6. The service `scheb_two_factor.security.google` takes number of digits as the first parameter in [two_factor_provider_google.xml](https://github.com/scheb/two-factor-bundle/blob/master/Resources/config/two_factor_provider_google.xml). The default is 6. Now if one wants to use more than 6 digits, one has to jump through the following hoops:
* Override `scheb_two_factor.security.google` to set the first constructor parameter to != 6
* Use this patch: https://github.com/sonata-project/GoogleAuthenticator/pull/103
* Modify `Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Google\GoogleAuthenticator::getQRContent()` to append the `digits` parameter (according to https://github.com/google/google-authenticator/wiki/Key-Uri-Format, keep in mind the "not yet implemented" comment is incorrect, Google Authenticator supports the digits parameter nowadays)

Example:
```php
public function getQRContent(TwoFactorInterface $user): string
{
    return parent::getQRContent($user) . '&digits=' . $this->passCodeLength;
}
```

It would be nice if this could be a configuration setting. What do you think?

**Comment by scheb** [comment]
Should be easy to implement and I think would be a great addition to have it configurable. I would implement that right away, but:

- I'm intentionally using version 1.1 of the Sonata bundle because for whatever reason the `GoogleAuthenticator` class is final in the 2.0 version, which makes it impossible to mock it in test cases.
- It doesn't look like they'd have a new release including that fix soon, so that I could reference it in the dependencies.

¯\_(ツ)_/¯

**Comment by Spomky** [comment]
Hi @scheb,

Could you please consider the use of another library: https://github.com/Spomky-Labs/otphp.
It offers support for a large range of digits (from 2 to .... whatever you want), large range of hash algorithms (in fact all the ones supported by PHP) and also additional features such as custom parameter.

Let's give it a try. I will be happy to help you by writing a PR if you agree with that.

**Comment by scheb** [comment]
@Spomky I'm not really tied to the Sonata bundle. If we can make the whole GA implementation more configureable by switching libs, well, why not... Send me a PR and we have a deal ;)

**Comment by lstrojny** [comment]
@scheb hah, final class without an interface is indeed uncivil, although one could refrain from mocking and simply fixate the time to a deterministic value. 
Anyway, https://github.com/Spomky-Labs/otphp looks indeed promising (and usable in testing). Just one quick find, `OTP::generateURI()` would need some love to support https://github.com/google/google-authenticator/wiki/Key-Uri-Format more completely.

**Comment by scheb** [comment]
Yeah well, but who likes to depend on foreign code in their test cases, even when you can somehow force the behaviour to become deterministic...

I guess @Spomky would be happy to make some improvements to the one method, if we can switch libraries then and make life better for everyone ;)

**Comment by Spomky** [comment]
> @scheb hah, final class without an interface is indeed uncivil, although one could refrain from mocking and simply fixate the time to a deterministic value.

I've some missing interfaces or public methods in the interfaces. I will update accordingly. Final classes should not be a problem as interfaces with all public methods exist.

> Just one quick find, OTP::generateURI() would need some love to support https://github.com/google/google-authenticator/wiki/Key-Uri-Format more completely

The library already supports Key Uri Format completely. Even custom keys are allowed (e.g. `image` supported by FreeOTP).

The only issue I see is that the bundle only stores the secret. It would be nice if we could store the whole provisioning uri. This way you don't have to care if the OTP uses 4, 6 or 20 digits, if the hash function is sha1 or sha512, if the period is 60 sec instead of 30.

**Comment by lstrojny** [comment]
@scheb indeed, depending on an implementation is not really fun.

@Spomky the proposal would be to store the whole OTP URI instead of just the secret? That sounds indeed very reasonable and would provide cryptographic agility as a bonus feature. Meaning changing the hash sum to something not sha1 in a working deployment wouldn’t break existing functionality.
What would be required for that is a URI parser, so that one can extract the secret from the URI. Is that something you would be interested in implementing?

**Comment by Spomky** [comment]
> What would be required for that is a URI parser, so that one can extract the secret from the URI. Is that something you would be interested implementing?

Already implemented : https://github.com/Spomky-Labs/otphp/blob/v9.0/doc/Factory.md

**Comment by lstrojny** [comment]
@Spomky lovely!

**Comment by Spomky** [comment]
> Meaning changing the hash sum to something not sha1 in a working deployment wouldn’t break existing functionality.

This is exactly what I tried to explain in the following page: https://github.com/Spomky-Labs/otphp/wiki/What-should-I-store-in-my-server-database

**Comment by umpirsky** [comment]
> I'm intentionally using version 1.1 of the Sonata bundle because for whatever reason the GoogleAuthenticator class is final in the 2.0 version, which makes it impossible to mock it in test cases.

Is it reported?

**Comment by scheb** [comment]
No, because this is not a bug, they did it intentionally to close their API: https://github.com/sonata-project/GoogleAuthenticator/commit/f53b45f5001ece04c275b786211f779042a0a00d

I'd then rather wanto to migrate to something open and maintained. But on the other side, the sonata bundle version 1.x worked fine so far, so I didn't migrate it yet. Also, no one else volunteered to migrate to something else, e.g. the Spomky-Labs/otphp library mentioned above, that's why we're still where we are right now.

**Comment by umpirsky** [comment]
I understand you, but I don't understand Sonata.

**Comment by Spomky** [comment]
Hi guys,

I am so sorry, I was quite busy and I missed that one.
I will try to propose a PR by the end of the week.

**Comment by Spomky** [comment]
@scheb On-going PR to help you to fix that. See #148 

@umpirsky a `final` class is not a bad practice. This is what Marco Pivetta (Ocramius) explains in one of its blog post and what I rewrote [in that section of Clean Code for PHP](https://github.com/jupeter/clean-code-php#prefer-final-classes). But the only rule to be respected is completely ignored by Sonata…

Anyway, I hope the changes made to this bundle by #148 will help you.

**Comment by greg0ire** [comment]
> I understand you, but I don't understand Sonata.

All you need to understand about Sonata is that we are open to discussion, and accept PRs. Don't assume we will let you stay stuck with 1.0 for such reasons. I think a PR to add an interface will be accepted so that you can do your mocking.

**Comment by umpirsky** [comment]
Done in https://github.com/sonata-project/GoogleAuthenticator/pull/111. Thanks!

**Comment by greg0ire** [comment]
Expect a release by tomorrow morning :)

**Comment by greg0ire** [comment]
Here you go: https://github.com/sonata-project/GoogleAuthenticator/releases/tag/2.2.0

**Comment by scheb** [comment]
v3.9.0 supports configurable digits.
