### ISSUE TITLE
Ability to use custom url for 2FA

### ISSUE THREAD

**Issue by umpirsky** [scheb/two-factor-bundle#133]
### Why?

When you have url based HTTP caching, using existing urls for 2FA can cause issues.

### How

Currently it's not easy. One idea is to override `RequestListener` and redirect to some specific `/2fa` route which will serve the form. This is not optimal because 2FA code will run twice.

**Comment by scheb** [comment]
If you have URL-based caching, why aren't you excluding pages with dynamic/user-specific content from the cache?

**Comment by umpirsky** [comment]
Because I need it cached. :)

**Comment by scheb** [comment]
Sorry, but that doesn't help. I don't understand why you need to have a form cached, which is just living for that single moment. From what I know now (which is not much), it sounds more like an issue with your caching concept to me, so you should fix that and start caching more selectively, instead of artificially changing URLs to bypass the cache.

**Comment by umpirsky** [comment]
Forget caching, I want to have 2FA living on certain url. 

Currently possible with:

```php
class RequestListener extends BaseRequestListener
{
    private $router;

    public function __construct(
        AuthenticationContextFactoryInterface $authenticationContextFactory,
        AuthenticationHandlerInterface $authHandler,
        TokenStorageInterface $tokenStorage,
        UrlGeneratorInterface $router,
        array $supportedTokens,
        $excludePattern
    ) {
        parent::__construct($authenticationContextFactory, $authHandler, $tokenStorage, $supportedTokens, $excludePattern);

        $this->router = $router;
    }

    public function onCoreRequest(GetResponseEvent $event)
    {
        parent::onCoreRequest($event);

        if (!$event->hasResponse()) {
            return;
        }

        if ('2fa' !== $event->getRequest()->attributes->get('_route')) {
            $event->setResponse(new RedirectResponse($this->router->generate('2fa')));
        }
    }
}
```

But as I pointed out, this is not optimal because 2FA code will run twice.

**Comment by scheb** [comment]
Wait, are we talking about bundle version 2.x?

**Comment by umpirsky** [comment]
Oh, yes, sorry.

**Comment by scheb** [comment]
Well, in that case... now I understand the whole caching issue since the 2.x version just displays the form on whatever URLs is being called. That's one of the many limitations of the 2.x implementation, which have been solved with the 3.x rewrite. As you've already spotted, the form has it's own controller and the bundle in fact redirects instead of just showing the form.

I'd really recommend you [upgrading](https://github.com/scheb/two-factor-bundle/blob/master/UPGRADE.md). The new version also has proper integration into the security layer, which alone is worth the effort.

**Comment by umpirsky** [comment]
I see, great. Thanks!
