### ISSUE TITLE
TwoFactorListener::hasTrustedDeviceParameter should check whether trusted feature is enabled

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#159]
At this moment it is implemented as

```php
    private function hasTrustedDeviceParameter(Request $request): bool
    {
        return (bool) $request->get($this->options['trusted_parameter_name'], false);
    }
```
while it probably should take into account logic similar to one from the `FormController`:

```php
$displayTrustedOption = $this->trustedFeatureEnabled && (!$config->isMultiFactor() || 1 === count($pendingTwoFactorProviders));
```

**Comment by scheb** [comment]
It's intentionally not checked there, because the decision, if the trusted feature is used or not, is made on the layer of `TrustedDeviceManagerInterface`. When it's disabled, there is a `NullTrustedDeviceManager`, which is not doing anything. The complexity in the layers above can therefore be reduced.
