### ISSUE TITLE
Don't require two-factor-authentication if access_control doesn't require authentication

### ISSUE THREAD

**Issue by Alsciende** [scheb/two-factor-bundle#16]
A part of my security.yml reads

    access_control:
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY } # for FOSJsRoutingBundle

But when the user is logged in and before the security token is validated, all requests to this path `^/js/` are blocked by two-factor-bundle. In my opinion, the `access_control` should prevent two-factor-bundle from blocking this path.

**Comment by scheb** [comment]
Unfortunately this is not possible since the bundle is not part of Symfony's security/authentication layer. Instead it is built on top of it, which means the security rules don't have any effect.

To exclude certain routes from being blocked by the two-factor authentication page, you can add a regex rule to the `exclude_pattern` [option](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md).

**Comment by Alsciende** [comment]
Thank you for your answer and the solution.
