### ISSUE TITLE
Form handling, CSRF, auth_code_parameter_name

### ISSUE THREAD

**Issue by quentinus95** [scheb/two-factor-bundle#166]
Hi,

I'm trying to upgrade to the last major version of the bundle but I'm stucked with the new implementation (for custom providers).

I want to use a form type for my 2FA page (as I was doing with the previous version of the bundle).

With the new version, there is a `auth_code_parameter_name` to specify which field handles the code. This is an issue because when using form types, the value is in an array.

```php
$request->get($this->options['auth_code_parameter_name'], '');
```

This line in the `TwoFactorListener` does not allow using a form type. Moreover, I want to do a CSRF check using the convenient `$form->isValid()` method, which would give me more flexibility.

Is there a way to bypass the `validateAuthenticationCode` and receive the `$request` instead, so I can do the check myself? If not, could you use the PropertyAccessor as Symfony does? (see `security\Http\ParameterBagUtils.php` in Symfony security component).

I guess `auth_code_parameter_name` should have the exact same behavior as `username_parameter` in `form_login`.

Thx

**Comment by scheb** [comment]
I see what you're trying to do. The v3 implementation is, because of the fully integrated security layer, mostly oriented on what the login form is doing.

I can at least help you with the fields issue. According to [this PR](https://github.com/symfony/symfony/pull/2936) you can have an empty root name for the form, which would effectively push all fields to the top level of the POST array. Shouldn't be a problem to read the auth-code then.

The second one is more comlicated and I don't have a solution for this. The authentication is layer is not using forms and form validation, so I don't know how you'd want to integrate form validation into that. Maybe replacing the `TwoFactorAuthenticationProvider` service with something else would work. But even if you'd manage to do that, I don't see how you could show the validated form together with its validation errors, since the auth-code-check is happening on a different route and the security layer is always doing a redirect back to the form, therefore losing the validation result.

`ParameterBagUtils` is a good idea btw., did not know about this before. Will add this for reading the parameter.

**Comment by quentinus95** [comment]
Hi @scheb, thanks for your help!

With the empty root, I can get the `auth_code_parameter_name` to work.

Putting the form validation appart, is there any way to pass custom errors to the `getFormRenderer()` method? What I was planning to do is this:

```php
public function getFormRenderer(): TwoFactorFormRendererInterface
{
    $form = $this->formFactory->create(SecondFactorType::class);

    $this->formRenderer
        ->setForm($form)
        ->setTemplate($this->challenger->getTemplate())
    ;

    return $this->formRenderer;
}

public function validateAuthenticationCode($user, string $authenticationCode): bool
{
    $result = $this->challenger->getChallengeResult($user->getSecondFactor(), $authenticationCode);

    if (!$result->isSuccessful()) {
        $this->formRenderer->setLastResult($result); // useless because of the redirect

        return false;
    }

    return true;
}
```

What I would like is to use the `$result` returned by a custom service, which contains some insights for the user on why the last authentication failed (or potentially some security warnings).

Sadly, it seems that there is a redirect if `validateAuthenticationCode` returns false (which sounds logical), so the only solution to avoid losing this message would be to use a flash message.

Am I right or there is a cleaner way to do this?

Thanks again!

**Comment by scheb** [comment]
One way of passing in custom errors would be to throw a `InvalidTwoFactorCodeException` (or any other instance of `Symfony\Component\Security\Core\Exception\AuthenticationException`) in the `validateAuthenticationCode` method, Then, the exception's error message will show up as `authenticationError` in the authentication form, just like the default message. Because of execution order, this would bypass the backup code check, but if you're not using that feature, it would work.

The alternative way would be to persist the error message in the session and extend the default `FormController` to read the error message from the session, remove it, and pass it to the template. All methods in the `FormController` are protected, so should be easy to hook in some additional code.

**Comment by quentinus95** [comment]
Ok @scheb, I'll go with the `InvalidTwoFactorCodeException`. Thanks for your help and time!
