### ISSUE TITLE
Generate Backup Codes

### ISSUE THREAD

**Issue by aguidis** [scheb/two-factor-bundle#171]
I'm a bit confused with the documentation related to the **Backup Codes**.

> The example assumes that there are already codes generated for that user.

Does your bundle allow to generate them ? or should we install another php library to achieve this goal (maybe you already know a specific package) ?

Based on this [topic](https://security.stackexchange.com/questions/62640/generating-backup-codes-for-a-2fa-implementation):

> Usually the backup codes are opaque random credentials, not mathematically based on the 2FA seed or anything else known about the user

Do you think a simple `random_int(100000, 999999)` would be enough ?

I didn't find any information in the documentation concerning this feature.

Thanks

**Comment by scheb** [comment]
The bundle doesn't do the backup code generation for you, it doesn't really care where these backup codes are coming from. It's just providing you a way to connect your backup codes (wherever these are stored) to the bundle using the `BackupCodeInterface` or `BackupCodeManagerInterface`. The implementation is then up to you.

I'm not a security expert, but from what the documentation says `random_int` should be good enough. In then end the codes should be distinct enough so that they cannot be guessed or derived from any user-related information.

**Comment by aguidis** [comment]
Ok I see... Indeed your library does provide an elegant way to sign in with a backup code :)

Thanks for you quick answer
