### ISSUE TITLE
Best way to require 2FA outside of IP whitelist even if user doesn't have secret set?

### ISSUE THREAD

**Issue by markbeazley** [scheb/two-factor-bundle#174]
On a project I am working on, we only require 2FA if the users is connecting from an IP outside of our IP white list, from what I can tell from the documentation there is no option to require 2FA to allow log in (which makes sense if you don't have a white list as no one would be able to login to add 2FA). The best I've managed to do with this if for users with out a secret set up is to have public function getGoogleAuthenticatorSecret(): string return a null which obviously causes an unhanded exception which isn't an ideal way to handle it. 

Have I missed a way to handle this better in the module? Or would it be possible to add an option to require 2FA outside of the whitelist?

**Comment by scheb** [comment]
Not sure if I understand your use-case. For user accessing from outside of the IP whitelist, you want to enforce 2fa, even when they don't have a 2fa provider configured? Basically, not letting them pass and telling them insteady they must configure 2fa to get access. And within the IP whitelist people would just by-pass 2fa, giving them the ability to configure 2fa for their account, which would enable them to access from outside of the IP whitelist.

Did I get that right?

**Comment by markbeazley** [comment]
Yeah that sounds right, basically 99% of the time users would be connecting from within the whitelist, but in some cases users may have to connect using mobile data as a fall back if the main internet connection at their location fails and as we don't have static IPs assigned on the mobile fallback connections I can't add them to the whitelist.

**Comment by scheb** [comment]
I've thought a bit about this, I think the best solution would be to implement a [custom two-factor provider](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/custom.md), which triggers only if there's no other two-factor provider enabled for that user. Then, have that provider never accept any authentication code. And instead of the authentication form, you'd render a message, telling the user that they're not allowed to pass until they're registered a two-factor authentication method from within the whitelisted IP range.

**Comment by markbeazley** [comment]
Yeah, that seems like that would work, thanks.
