### ISSUE TITLE
[Idea] Use guard instead of firewall listener

### ISSUE THREAD

**Issue by B-Galati** [scheb/two-factor-bundle#180]
Hello!

What do you think about providing a guard instead of a firewall listener?

It would greatly simplify the bundle and DX (easier to customize) perhaps no need for custom events anymore.

For example, that's what https://github.com/knpuniversity/oauth2-client-bundle/ is doing while https://github.com/hwi/HWIOAuthBundle is providing a firewall listener.

Cheers!

**Comment by scheb** [comment]
Can you elaborate what the advantage of a guard implementation would be?

To be honst, I've never understood the guard concept, but I haven't really built a Symfony application in more than 3 years.

Not sure if a guard is even capable of doing what the bundle is doing, since it's not providing a way to identify yourself as a specific user, but hooking into the authentication mechanism to introduce another step into the authentication process and that requires some low-level action on the security layer.

In the end, I believe it doesn't matter how it's implemented under the hood. As the developer using the bundle, you shouldn't actually bother yourself with these implementation details. If you're configuring a guard or a firewall listener, that's in the end just configuration.

**Comment by B-Galati** [comment]
Not a specialist but before guard, hooking into the security flow of Symfony was quite a pain. Specially if you wanted to do a Firewall listener and everything that allows you to have good a control of everything.

Tha's why guard was created. It gives developers a simple way to add a custom Authentication process within your app. Only 1 class is required and the configuration is simple.

>Not sure if a guard is even capable of doing what the bundle is doing, since it's not providing a way to identify yourself as a specific user, but hooking into the authentication mechanism to introduce another step into the authentication process and that requires some low-level action on the security layer.

I don't know either, it would require a PoC :+1: .

>In the end, I believe it doesn't matter how it's implemented under the hood. As the developer using the bundle, you shouldn't actually bother yourself with these implementation details. If you're configuring a guard or a firewall listener, that's in the end just configuration.

I agree but IMHO guard would give 2 advantages :

- It would be more simple to customize the bundle behavior for developers
- Less code and less complicated code to maintain within the bundle

**Comment by scheb** [comment]
Checked the guard implementation. It's closely related to the use-case of user identification+authentication based on information passed in the request. So everything that goes like:

- Detect a request as an authentication attempt
- Get user identification data from the request
- Find the user account in the "user database"
- Validate credentials of that user - or fail
- When credentials have been valid, have an authenticated user

Its main advantage is that it's abstracting away the glue between those steps by providing a generic implementation and letting you fill the gaps.

The built-in concept is unfortunately not compatible with the 2fa process. Using a guard would mean somehow working around the use-case it has been built for, which would probably be less code, but more hacky code. The firewall listener is in fact more complex to implement and requires more boilerplate, but it is more flexible, because it doesn't make so many assumptions about how to use it. So I'm going to stick with the current implementation.
