### ISSUE TITLE
Unauthenticated token after successful 2FA token 

### ISSUE THREAD

**Issue by aplusphilic** [scheb/two-factor-bundle#188]
Hello

I have been using this bundle v2.14 for a while now and it has been working great for me. Recently I decided to upgrade to v3.16 after I have upgrade my application to Symfony 3.4. I have successfully setup the bundle in the application and configured it and I'm able to login and verify token both for email and google authenticator but the issue that I'm facing is that the I keep on being asked to enter 2FA token every-time and checking the token is always an instance of TwoFactorToken.

What I have noticed after aI have gone through the code and dump the token in TwoFactorListener.php on line 254. This is what I get `UsernamePasswordToken` with authenticated set to false.

<img width="335" alt="screen shot 2018-12-03 at 12 29 08" src="https://user-images.githubusercontent.com/3054451/49365172-269d5400-f6f7-11e8-827a-7a5e18d75752.png">

and this is after `$response = $this->successHandler->onAuthenticationSuccess($request, $token);` has been called.

Is this correct? Is there anything that I'm missing?

**Comment by scheb** [comment]
> What I have noticed after aI have gone through the code and dump the token in TwoFactorListener.php on line 254. This is what I get `UsernamePasswordToken` with authenticated set to false.

Can you please point me to the line in the code? If I look up [Line 254 in v3.16](https://github.com/scheb/two-factor-bundle/blob/1c9ec9285ea5c1fc72891a6e0012ea03d5c148f7/Security/Http/Firewall/TwoFactorListener.php#L254) is something unrelated.

The fact that your `UsernamePasswordToken` is unauthenticated may be a problem. I checked in my test environment and there the token is authenticated=true before it's wrapped with the `TwoFactorToken` and it's still like that after it has been unwrapped. So this is something you should investigate.

For further investigation, can you please check if you end up in [this line](https://github.com/scheb/two-factor-bundle/blob/2be8d05b2e46c8e34bd9f596f73c19ca84b2f602/Security/TwoFactor/Handler/TwoFactorProviderHandler.php#L51) AFTER two-factor authentication has been completed? (Of course, it should be called after login, when the two-factor process is initiated). If it's called another time, it would explain, why you continue to see a `TwoFactorToken` instead of the `UsernamePasswordToken`.

**Comment by scheb** [comment]
Please also check which bundle version you're on. From the non-matching line numbers, I'd guess it's not v3.16.

And please also post the exact Symfony version you're using. E.g. 3.4.12 is known to have a problem with lazy-loading services, which could lead to unexpected behavior.

**Comment by aplusphilic** [comment]
Hi @scheb 
The screenshot shared above might be misleading in terms of the line number but while I was checking what might be the issue I was adding bunch of `dump()` function to check why the issue was happening. The exactly line I added the dump shown in the screenshot is here [on Line 250](https://github.com/scheb/two-factor-bundle/blob/1c9ec9285ea5c1fc72891a6e0012ea03d5c148f7/Security/Http/Firewall/TwoFactorListener.php#L250) 

I'm on v3.16, the line mismatch its because of me adding random `dump()` functions, sorry about that

**Comment by aplusphilic** [comment]
> For further investigation, can you please check if you end up in [this line ](https://github.com/scheb/two-factor-bundle/blob/2be8d05b2e46c8e34bd9f596f73c19ca84b2f602/Security/TwoFactor/Handler/TwoFactorProviderHandler.php#L51)AFTER two-factor authentication has been completed? (Of course, it should be called after login, when the two-factor process is initiated). If it's called another time, it would explain, why you continue to see a TwoFactorToken instead of the UsernamePasswordToken.

This gets called immediately AFTER successful login and looking at the TwoFactorToken contains authenticated token. Look at the screenshot. Please disregard the line numbers in the screenshot as I have added `dump()` function call.
<img width="512" alt="screen shot 2018-12-04 at 14 12 00" src="https://user-images.githubusercontent.com/3054451/49438260-e8736380-f7ce-11e8-9760-ad3bd926cbd0.png">

Trying to figure out where the token `authenticated` value changes to `false` when it gets to `TwoFactorListener` on `onSuccess` method

**Comment by scheb** [comment]
> This gets called immediately AFTER successful login and looking at the TwoFactorToken contains authenticated token.

If I read that right, you're not getting another call to that line, when you complete two-factor authentication? If so, great, then you should focus on finding out why the token becomes unauthenticated at some point.

**Comment by aplusphilic** [comment]
@scheb Yeah I'm not getting another call on that line. Trying to hunt down at what point where token become unauthenticated. By any chance can you guide me on the flow as to what journey in the code the token goes through so that I can troubleshoot this.
