### ISSUE TITLE
AuthenticationContextInterface in form renderer

### ISSUE THREAD

**Issue by madwizard-thomas** [scheb/two-factor-bundle#195]
I'm trying to implement a webauthn provider for your bundle and came across some hurdles I would like to hear your thoughts about. I can work around them but maybe there's something to take into consideration for the next version.

For webauthn a challenge and a set of credential IDs is presented to the user agent and it will respond with an object structure that is usually converted to JSON and posted back to the server. The focus of two-factor-bundle is very much on entering a code in a field (e.g. the default form and the validateAuthenticationCode method). Since there is no manual input with webauthn I have to use a different form renderer and template and make the authentication code a hidden field that will contain JSON. This seems a bit hacky since there is no actual authentication code but it works. 

However to create the challenge (in the form renderer) I need the exact user,  but the form renderer does not have this directly. I can get the token from the token storage and extract the user that way, but wouldn't it be more logical to also add the AuthenticationContextInterface to the render phase?

The context is passed to beginAuthentication where I could create the challenge but there would be no clean way to pass it on to the render phase.

**Comment by scheb** [comment]
That's pretty much how I'd implement this.

The authenticatication code field can be used to pass whatever information is necessary to authenticate the user. Think about it more like "credentials", it is named "authentiction code" because that's what it's mostly used for. In the end it doesn't really matter to the bundle what you pass there, it's just some value required for authentication.

For rendering the form I think it's totally valid to get the user from the token storage. That's what anyone would do in Symfony, if they need to current user for an operation. Of course, I see that it would be more convenient, if that information would already be passed into the form renderer, but I wanted to keep the method signature to the minimum, especially since Symfony has the ability to inject any kind of additional information required into the renderer.

**Comment by scheb** [comment]
Closing. Feel free to re-open if you have some more questions on this topic.
