### ISSUE TITLE
Setting success_handler on json_login prevents two-factor authentication

### ISSUE THREAD

**Issue by MichaelKubovic** [scheb/two-factor-bundle#220]
**Bundle version**: 4.x, likely 3.x as well
**Symfony version**: 4.2.7

**Description**

When any success handler is configured for Symfony's `UsernamePasswordJsonAuthenticationListener`, then the success handler creates the response and the json authentication listener sets the response for the firewall. The token it retrieves is the `TwoFactorToken`, but the json_login listener doesn't care. `TwoFactorListener` is not not notified and the authentication request ends with 200 Ok :)

**To Reproduce**

I have fixed the problem by having my success handler aware of two-factor authentication and respond accordingly but obviously that's not desirable :)

I was thinking about a compiler pass decorating all the configured success_handlers. The decorator would delegate to existing `AuthenticationRequiredHandlerInterface`.

**Comment by MichaelKubovic** [comment]
Here is the condition that ends the request prematurely. https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordJsonAuthenticationListener.php#L186

**Comment by scheb** [comment]
From `UsernamePasswordJsonAuthenticationListener`:

> UsernamePasswordJsonAuthenticationListener is a stateless implementation of
> an authentication via a JSON document composed of a username and a password.

How do you pass two-factor authentication, when the whole thing is stateless and there is no itermediate "awaiting two-factor authentication" state?

To better understand the problem, could you share what you did in your own custom success handler?

**Comment by scheb** [comment]
@MichaelKubovic Any update on this? Otherwise I'm closing this issue.

**Comment by MichaelKubovic** [comment]
Sorry I linked the wrong line. I meant success handler, not failure handler.
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordJsonAuthenticationListener.php#L162

So the json_login does not have to be stateless. My implementation uses cookies the same way a form-post would. You send the ajax request from your page, that is served from your app, so you are on the same domain. the state on the server changes and the cookie is present on all ajax requests so the authentication is stateful.

The ajax request with valid credentioals is handled by the json_login listener, that delegates and eventualy autenticates the token. Decorator swaps the token for the `TwoFactorToken`.

At this step I would expect json_login listener to catch that it didn't get authenticated token back. But because no `AuthenticationException` was thrown, the listener executes further.

Now, when there is no success handler defined on json_login, Firewall delegates to next configured listener. The `TwoFactorListener` supports the new token, it kicks in and eventualy does the right thing. It dispatches `TwoFactorAuthenticationEvents::REQUIRE`.

I implemented `TwoFactorAuthenticationRequiredHandler` to return a nice ajax-friendly response for the request. The session cookie is delivered together with the response body so the `TwoFactorToken` is persisted between requests.

To get back to the issue, the success handler in the json_login listener prevents `TwoFactorListener` to act on a newly created `TwoFactorToken`.

Following snippet illustrates how did I overcome this inconvenience.
```php

    public function onAuthenticationSuccess(Request $request, TokenInterface $token): Response
    {
        // setting success handler on json_login firewall listener stops the request prematurely
        // https://github.com/scheb/two-factor-bundle/issues/220
        if ($token instanceof TwoFactorTokenInterface) {
            // prepare provider, e.g. send sms
            $this->eventDispatcher->dispatch(
                TwoFactorAuthenticationEvents::REQUIRE,
                new TwoFactorAuthenticationEvent($request, $token)
            );
            return $this->twoFactorRequiredHandler->onAuthenticationRequired($request, $token);
        }
...
    }
```

**Comment by scheb** [comment]
I believe there's a misperception how the bundle works. The `TwoFactorListener` is never called _within the same request_ as the `UsernamePasswordJsonAuthenticationListener` (or any other listener providing initial login). Usually the process goes like this: User does a successful login, the login redirects to a target page. At this stage there's a `TwoFactorToken` present in the session, but nothing has happened yet. If that target page requires the user to be completely authenticated (including two-factor authentication) the `TwoFactorListener` will prepare the two-factor authentication provider and redirect to the two-factor authentication form. There are some internal reasons why it works that way.

But anyways. Form what I understand, you want the following:
- You want a JSON API to authenticate the user.
- On the login request, the API should respond with a JSON message telling the frontend to require two-factor authentication.
- Therefore the two-factor provider needs to be prepared right on the login request, because you don't have a subsequent request to the API that would trigger preparation. (This currently a problem with bundle version 4.x because of #212).

What I would suggest as a solution:
- Give the [require-event-fixes](https://github.com/scheb/two-factor-bundle/tree/require-event-fixes) branch a try. It's intended to solve the problem with the two-factor provider preparation.
- Since the `TwoFactorListener` is not executed within the login request, replace the success handler from `UsernamePasswordJsonAuthenticationListener` and return the JSON response there. When that handler is triggered there's already a `TwoFactorToken` present, so you know if two-factor authentication is required or not.

**Comment by MichaelKubovic** [comment]
A workaround that you suggested is indeed what I have've done to continue with work.

The `TwoFactorListener` is called within the same request, as long as the preceding listener does not return a response. Which is the case for json_login listener by default. https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Http/Firewall.php#L145

**Comment by scheb** [comment]
> The TwoFactorListener is called within the same request, as long as the preceding listener does not return a response. Which is the case for json_login listener by default. https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Http/Firewall.php#L145

True, but as far as I understand this piece of code, the intention of this statement is to stop execution when you've found an authentication listener that felt responsible for handling the request and therefore created a response. I don't think chaining listeners was meant to be a feature.

**Comment by MichaelKubovic** [comment]
The json_login listener is designed to authenticate the user and let the framework invoke the configured controller upon success . When you enable two-factor, what would you say would be expected behaviour? I would expect that the controller is not invoked as I have not passed authentication fully. While it is true that subsequent requests would behave correctly (because TwoFactorToken is already in session), I would like to fix it for this edge-case.

Let me have a look at how `require-event-fixes` branch affects this case. I'll get back to it in a few days, please bear with me.

**Comment by scheb** [comment]
I'm closing this issue now, because I believe this is not under control of the bundle and therefore I won't be able to provide a fix for this.

The suggested solution is to add a custom success handler to the json_login authentication provider in your application. One that can tell if the user requires two-factor and can return the right JSON response.
