### ISSUE TITLE
Trusted device settings firewall based

### ISSUE THREAD

**Issue by bytehead** [scheb/two-factor-bundle#236]
Hi Christian 👋 

In my scenario I have multiple firewalls with 2FA and trusted devices enabled. With the way it is right now it's not possible to have different cookie names on different firewalls. Therefore the cookie(s) get overwritten when the firewall changes.

It would be nice to have the trusted device config firewall based instead of bundle based.

If you consider this as a possible feature, I would like to provide a draft PR as a base for further discussions.
What do you think?

**Comment by scheb** [comment]
Hmm, I had a quick look into the code, not sure what the issue is. Trusted token - although they're written to the same cookie - are scoped by firewall name. The trusted token manager should just ignore token from a different firewall and retain them in the cookie. But to be honest, I've never tried it on a real-world example.

Do you have an idea what piece of the code causes the other firewall's token being removed?

**Comment by bytehead** [comment]
Then I misunderstood the concept 🙈 Thanks for clarification! I'll try this and reopen if needed.
