### ISSUE TITLE
User is not in a two-factor authentication process.

### ISSUE THREAD

**Issue by katerina-n** [scheb/two-factor-bundle#241]
Hello,

Could you please provide me with some assistance? I'm integrationg your bundle in my project and getting an error "User is not in a two-factor authentication process." What am I doing wrong? Here are configurations

```
main:
            pattern:             .*
            context:             user

            anonymous:          true
            logout:
                path: fos_user_security_logout
                target: /
                invalidate_session: false # not clears all session data and regenerates session ID
                success_handler: lightsaml.logout_success_handler


            switch_user: true
            guard:
                authenticators:
                    - precoro.security.login_form_authenticator
                    
            two_factor:
                auth_form_path: 2fa          # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
                default_target_path: /
                provider: fos_userbundle
```

**Comment by scheb** [comment]
1) Please provide the bundle and Symfony version that you're using.

2) When you see that error message, what kind of token is present in the session? You can get that from the profiler/debug toolbar. It's definitely not a `TwoFactorToken` because that's the reason for the error.

3) Is your guard authenticator redirecting to the `2fa` route? I'm wondering how you end up on that page when you don't have a `TwoFactorToken` (as mentioned above).

**Comment by katerina-n** [comment]
I'm using Symfony 3.4 and two-factor-bundle 4.7. Tokens type is PostAuthenticationGuardToken and i set ot to config:
security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken


No, it doesn’t redirecting, sorry this is my mistake, didn’t clean the browser cache.  Now, after entering the email and password I am not redirected to / 2fa

**Comment by scheb** [comment]
When you see the `PostAuthenticationGuardToken` instead of `TwoFactorToken` after login and therefore you're not redirected to the 2fa route

- your user account didn't fulfill the requirement to do two-factor authentication
- or you're coming from a whitelisted IP
- or you have a trusted device cookie set

Most likely the first one. Please follow the [troubleshooting guide](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/troubleshooting.md#two-factor-authentication-form-is-not-shown-after-login) "Two-factor authentication form is not shown after login".

**Comment by katerina-n** [comment]
Tanks a lot

**Comment by katerina-n** [comment]
My problem is problem 5:
returns an empty array:
Solution: our user doesn't have an active two-factor authentication method. Either the is*Enabled method returns false or an essential piece of data (e.g. Google Authenticator secret) is missing.

I checked the GoogleAuthenticatorTwoFactorProvider/beginAuthentication method, there is a value $user->getGoogleAuthenticatorSecret() = null

Could you plese tell me when this value has to be filled? When a user successfully passes login/password check?

Sorry for such a question, I just really want to clarify this.

Thanks

**Comment by scheb** [comment]
Google Authenticator requires a secret code, which is used to initalize the random generator for the authentication code.

Usually, this code is generated when the user creates the account or at a later point in the account settings (for example, Github has it on the [security settings page](https://github.com/settings/security). In the end, you have to share that code with the user - either display it so they can type it off or display the QR code to scan it - so they can add it into the Google Authenticator app on their mobile.

There's documentation [how to generate such a code](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/google.md#generating-a-secret-code) and what you need to generate a QR code.

**Comment by katerina-n** [comment]
Thanks a lot. You really help me.
