### ISSUE TITLE
TwoFactorProviderPreparationListener reopens session

### ISSUE THREAD

**Issue by mathieudz** [scheb/two-factor-bundle#257]
**Bundle version**: 4.11.1
**Symfony version**: 4.4.2

**Description**
When loading the TFA form (/2fa), the session is started, stopped and started again, because the bundle uses the session after Symfony has closed it. The session is open after processing the request.

**To Reproduce**
- Use native sessions in Symfony
- Put a breakpoint in NativeSessionStorage on every line that changes $this->started
- Start the debugger
- Log in
- When the /2fa page is hit, you'll notice:
1. session is started
2. session is stopped by Symfony's SessionListener (on kernel response)
3. session is started again by TFB's TwoFactorProviderPreparationListener (on kernel finish request) because it checks the content of the session
- When the request is finished, the session is not stopped

**Additional Context**  
When running this in PHP PM, the next request will fail as the session is still open from the previous request (will not try to start the native session as it thinks it's already started, and crash when it tries to save it, since the $_SESSION variable is not set).
The behavior is only really an issue when using PHP PM, but since Symfony closes the session cleanly, this bundle should respect that behavior and not reopen it.

**Comment by mathieudz** [comment]
Suggestion solution: move the preparation listener to on kernel response, before the session listener. If that's two soon, you could copy the relevant session content to the request at that time, so the preparation listener does not need the session anymore.
My workaround in the meanwhile is to add an additional listener on finish request that closes open sessions (again).

**Comment by scheb** [comment]
The reason why it's done "on request finish" and not "on response" is to move processing time for preparation operations to after the response, therefore not delaying the response. So I wouldn't want to move it to the "on response" event.

I had a look at the session implementation and it seems to be explicitly supported to restart the session after it has been saved by the `SessionListener`: https://github.com/symfony/http-kernel/blob/master/EventListener/AbstractSessionListener.php#L115-L119

The issue seems to be closely related to the PHP PM environment you're using. I believe it can be fixed by adding a `save()` call when the session is modified by `TwoFactorProviderPreparationRecorder`. I've created a new branch (https://github.com/scheb/two-factor-bundle/tree/save-session) with that change.

Would you please use the branch in your project and check if it's solving it?

**Comment by kpricorn** [comment]
I'm having the same or a similar issue when running codeception functional tests. The session parameters set in `recordProviderIsPrepared` are not persisted and the next call to `isProviderPrepared` fails. Switching to the save-session branch solves the issue for me. The issue first appeared in 4.7.0.

**Comment by scheb** [comment]
4.7 was when preparation state was remembermed in the session.

Looks like the `save()` is necessary in some environments. Ideally, I'd like to get feedback from @mathieudz before I add it to a release.

**Comment by mathieudz** [comment]
@scheb The patch doesn't fix it.
The session is started on https://github.com/scheb/two-factor-bundle/blob/28dc1c6b8e3d7f4b30a754366f0ad9181452f0a3/Security/TwoFactor/Provider/TwoFactorProviderPreparationRecorder.php#L25
It does not always reach https://github.com/scheb/two-factor-bundle/blob/28dc1c6b8e3d7f4b30a754366f0ad9181452f0a3/Security/TwoFactor/Provider/TwoFactorProviderPreparationRecorder.php#L39

**Comment by scheb** [comment]
Hmm, I see. Will need to investigate some more.

If you find a solution that works for you, feel free to provide it as a PR.

**Comment by scheb** [comment]
@mathieudz There's a new implementation available in the branch. Would you please check? Thanks!

**Comment by mathieudz** [comment]
@scheb Session is closed correctly with the new implementation.

**Comment by scheb** [comment]
Ok, great. There's a new release 4.13.0 with this change.
