### ISSUE TITLE
Enhanced authentication process

### ISSUE THREAD

**Issue by mathieudz** [scheb/two-factor-bundle#258]
I see two issues with the current authentication process, in particular how the user is redirected to the OTP form:
- It redirects too much: After providing user/pass, you're stuck on the OTP form unless you cancel. From the point of view of the user, as long as you didn't provide the OTP, you're not logged. Why can't you browse around as anon user without explicitly canceling the authentication process?
- It redirects not enough: If the user goes to a page with anonymous access control, the redirect does not kick in as the listener thinks it's for some resources that are needed for the OTP form. This leaves the user in limbo, unable to complete the authentication process

This all feels rather wonky. IMHO a better solution would be that after (and only after) logging in with the username & password (or whatever), the bundle forces a redirect to the OTF form, without checking access control. Additional care is needed to be sure that the user is still considered as "2fa in progress" and not fully authenticated as long as the OTP form was not successfully completed. The fact that the process was not completed is not an issue because the user can still use the website anonymously.

**Comment by scheb** [comment]
> It redirects too much: After providing user/pass, you're stuck on the OTP form unless you cancel. From the point of view of the user, as long as you didn't provide the OTP, you're not logged. Why can't you browse around as anon user without explicitly canceling the authentication process?

You can. Configure the parts of your page that should be accessed in that intermediate state in `access_control` with `IS_AUTHENTICATED_ANONMYOUSLY`. Then you can visit these pages even when you haven't completed 2fa.

> It redirects not enough: If the user goes to a page with anonymous access control, the redirect does not kick in as the listener thinks it's for some resources that are needed for the OTP form. This leaves the user in limbo, unable to complete the authentication process.

That's intentional, as described above. But I'd recommend, when you let people browse your page with incomplete 2fa, to show them some message that is telling them they've not authenticated yet and still need to complete 2fa (and linking to the 2fa form).

> This all feels rather wonky. IMHO a better solution would be that after (and only after) logging in with the username & password (or whatever), the bundle forces a redirect to the OTF form, without checking access control.

This is unfortunately the part that the bundle has no control of. The authentication provider that was initially used (such as username/password) is responsible for the redirect after the login. So you end up wherever that provider redirects you. If the target is a page that requires you to be fully authenticated the 2fa will kick in and lead you to the 2fa form. Otherwise, when the target can be accessed anonymously (as configured in `access_control`), the page will be shown and the 2fa form will only be shown once you visit a different page that requires you to be fully authenticated.

The reason why it is implemented like that is the way authentication is implemented in Symfony's security component. Multi-stage authentication - as required for 2fa - does not exist in Symfony. The bundle is working around this drawback in may ways, but there are certain limitations that is cannot solve.

**Comment by mathieudz** [comment]
This bundle is able to modify the behavior of the initial authentication provider (i.e. replacing the token), so it might be possible to intercept the redirect? I haven't looked into it.

**Comment by scheb** [comment]
It does not modify the authentication provider, it does that by decorating the authentication manager, which is a centralized and predefined service in the security component. You can rely on the service being there and you know its name.

Compared to that, authentication providers are much more of a black box. They don't need to follow a certain implementation pattern, they don't need to have a success or failure handler. So there's much less things you can rely on and that's what make it hard to reliably hook into them.

But since you're the developer of your application, you have much more insights. So, if you really need that forced-redirect behavior after the login, you could change the authentication provider's success handler with a custom one.

If you have an idea how to reliably influence the post-login redirect of any authenticatior provider, I'd love to hear.

**Comment by scheb** [comment]
Closing this since there's nothing actionable we can do right now.
