### ISSUE TITLE
Can't add csrf-token to form.html.twig

### ISSUE THREAD

**Issue by doker42** [scheb/two-factor-bundle#273]
**Bundle version**: 2.0.0
**Symfony version**: 2.7

**Description**
Can't understand how to add the csrf-token to AcmeDemoBundle:Authentication:form.html.twig

**Comment by scheb** [comment]
Bundle version 2.x is no longer supported and I seriously cannot recommend using it because of some security issues. As far as I remember 2.x never had CSRF protection, that feature was only introduced with version 3.x.

Please upgrade to a recent, still supported bundle version. Ideally the latest 4.x.
