### ISSUE TITLE
User is not in authentication process

### ISSUE THREAD

**Issue by faizan944** [scheb/two-factor-bundle#281]
@scheb  I faced an issue while integrating your two step verification package. I used symfony version 3.4 and two step verification bundle 3.17.0. 
Actually the issue is whenever I try to hit /2fa I got an error message "User is not in authentication process" Actually I used sonata admin as well so sonata provide its own table for user called "fos_user_user" and its configuration os only possible through xml so I am unable to implement "TwoFactorInterface" interface using xml.

**Comment by scheb** [comment]
> Actually the issue is whenever I try to hit /2fa I got an error message "User is not in authentication process"

Is the path `/2fa` within the firewall's `pattern`?

> Actually I used sonata admin as well so sonata provide its own table for user called "fos_user_user" and its configuration os only possible through xml so I am unable to implement "TwoFactorInterface" interface using xml.

I don't know the configuration options of fosuserbundle in detail, but I'm relatively sure you can implement your own user entity class and make it to use that one instead. Would allow you to implement the TwoFactorInterfaces, because with out these, two-factor authentication will not work.
