### ISSUE TITLE
Authentication success/failure event

### ISSUE THREAD

**Issue by silvioq** [scheb/two-factor-bundle#44]
Is it possible to observe an "authentication.failure" or "authentication.success" event? My user requirement is to lock the user account after "n" invalid authentication attemps.

Maybe I can add a dispatch event here https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Provider/TwoFactorProviderRegistry.php#L74 or here https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/EventListener/RequestListener.php#L74 but I'm not sure.

Sorry for my basic English.

**Comment by scheb** [comment]
Just to clarify, you're talking about the success/failure events for the two-factor authentication layer, right?

**Comment by silvioq** [comment]
Right! I'm talking about after login phase. 

I'm implementing some code on security.authentication.failure and security.authentication.success and I'm interesting in put this code in scheb_two_factor.authentication.failure ...

**Comment by silvioq** [comment]
Hi scheb, What do you think about something like this commit?

https://github.com/silvioq/two-factor-bundle/commit/208aa65fccdd39e125a3081258549dfa5fa3bc0e

**Comment by scheb** [comment]
The approach is good, but after looking at the code I have to say that a authentication failure event is currently not possible. Because of the way the two-factor authentication is implemented, it cannot distinguish between authentication failures and viewing the authentication form. That means just looking at the authentication form would also fire an authentication failure event, which is certainly not what we want.

Without some breaking changes for two-factor providers this cannot be implemented :/

**Comment by silvioq** [comment]
In that case, I must create a custom provider ...

**Comment by scheb** [comment]
That would work as a workaround. I'll keep the issue open for a potential 3.0 version.

**Comment by silvioq** [comment]
Well, I closed my user requirement with a very messy (but effective) patch

https://github.com/silvioq/two-factor-bundle/blob/patch-event/Security/TwoFactor/Provider/TwoFactorProviderRegistry.php#L93

**Comment by pmontoya** [comment]
I try to do the same but without BC break : #61

**Comment by pmontoya** [comment]
PR closed and new one created [#67](https://github.com/scheb/two-factor-bundle/pull/67)

**Comment by pmontoya** [comment]
Maybe you can close this one?

**Comment by silvioq** [comment]
Closed! Thanks!
