### ISSUE TITLE
Google Authenticator Timezone

### ISSUE THREAD

**Issue by umpirsky** [scheb/two-factor-bundle#56]
Sometimes two factor auth fails for me ("The verification code is not valid" flash message) and I suspect it may be a timezone issue. When it happens, I cannot login no matter how many times I try. After a day or two, I setup new secret and it works. It's pretty random.

I saw https://github.com/chregu/GoogleAuthenticator.php/issues/15 and not sure if it is related.

Is there any other reason why it can fail like this?

Thanks.

**Comment by scheb** [comment]
Time zones don't matter for Google Authenticator because it is using the Unix timestamp internally. As long as the time on the phone and the server is "in sync", which means they're no more than a few seconds apart. Server time can be manually/automatically synced with a time server. Phone time can be synced with Google servers in the options of the Google Authenticator app.

The only thing that could happen with time zones is that the time zone setting on the server/phone is not set correctly and therefore the machine cannot calculate the right UTC time and therefore the Unix timestamp would be wrong on one machine. But then you wouldn't get any valid codes at all, because the codes are only valid for 30 seconds.

**Comment by umpirsky** [comment]
@scheb Thanks for the quick answer.

Well time on my vm is `Thu Jul 14 00:02:02 PDT 2016` while time on the phone is `Thu Jul 14 09:02:02 PDT 2016`. 

This few seconds apart seems like a limitation, but I see time correction sync now in the phone app. Will try that if I manage to reproduce this issue again.

Thanks!

**Comment by nibornm** [comment]
Finding the sync option in the app, via the settings and then clicking "sync now" worked for me.
Thanks everyone.
