### ISSUE TITLE
Optimize RequestListener

### ISSUE THREAD

**Issue by umpirsky** [scheb/two-factor-bundle#59]
Looks like `RequestListener` adds some latency, and not `onCoreRequest` as you'd expect, but just fetching the service from container can add ~25ms to each request.

I tried to track down the dependency graph and it goes like this: `scheb_two_factor.security.request_listener` -> `scheb_two_factor.trusted_filter` -> `scheb_two_factor.provider_registry` -> `scheb_two_factor.security.google.provider` -> `scheb_two_factor.security.google.backup_code_validator` -> `scheb_two_factor.backup_code_validator` -> `scheb_two_factor.persister.doctrine`.

If using [lazy services](http://symfony.com/doc/current/service_container/lazy_services.html) and check `FlagManager.isNotAuthenticated()` [earlier](https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/EventListener/RequestListener.php#L80) this can be optimized.

I know `FlagManager` does not know about providers, but maybe it can be tweaked to pull a minimal set of dependencies if `FlagManager.isNotAuthenticated()` is `false`.

**Comment by scheb** [comment]
The 25ms seem a little bit too high for me for just fetching a service. DIC in prod should be able to do that way faster. Did you measure those values in a "dev" or a "prod" environment? Do you have some op-code cache enabled, either APC or native PHP7 op-code cache?

Anyways, there IS room for improvment.

I think a major improvment would be if `scheb_two_factor.provider_registry` would lazy-load the authentication provider services, because it only needs the service instance, when two-factor authentication has to be executed. But I wouldn't like to require the `ocramius/proxy-manager` on the bundle-level. Using that is more of a application-level decision, that the user has to do, and i don't want people force using it. So a simple "AuthenticationProviderFactory" that fetches the service from DIC on-demand would be the best solution im my opinion.

**Comment by umpirsky** [comment]
@scheb Yes, it is too high, that's why I'm posting. Other services are fetched way faster. It's from Blackfire profile done on prouduction with op-code cache enabled. Thanks.

**Comment by zerkms** [comment]
So, what exactly consumes those 25ms?

**Comment by umpirsky** [comment]
@zerkms Fetching service from container:

![screenshot from 2016-08-03 12-07-58](https://cloud.githubusercontent.com/assets/208957/17361883/f6724642-5972-11e6-9c3d-736626806f98.png)
![screenshot from 2016-08-03 12-07-23](https://cloud.githubusercontent.com/assets/208957/17361886/f956eb42-5972-11e6-8c6c-69592074717d.png)

**Comment by zerkms** [comment]
Right, but what exactly takes so long? 26ms is **A LOT**. Nothing but few objects are instantiated there.

On my projects some of entire requests (from the first request byte to the last request byte) take less than that.

I would still suggest to find the *real* problem before trying to optimise it, since it looks suspicious.

**Comment by umpirsky** [comment]
@zerkms Yes, I agree, still investigating it. Only services from this bundle are loading this slow.

**Comment by umpirsky** [comment]
Here are the latest findings. Making `scheb_two_factor.provider_registry` service lazy lowers down latency by double. Making `scheb_two_factor.trusted_filter` makes latency go away, no services from this bundle are shown in Blackfire profile, which means bottleneck is gone.

@scheb I think requiring `ocramius/proxy-manager` is totally worth it.

**Comment by scheb** [comment]
https://github.com/scheb/two-factor-bundle/commit/e9f3d5e309134b2ba9e6d8b08be5221e9fb33247

Release will be published as soon as Travis build greenlights the change.

**Comment by umpirsky** [comment]
@scheb Awesome, thanks! :+1:

**Comment by zerkms** [comment]
Well, I checked code and I'm not convinced that it should have been implemented like that.

The current solution mitigates the consequences but does not solve the root of the problems (since the roots haven't been detected).

Adding `lazy` to something that looks like slow but is not proven to be the problem - is crazy.

**Comment by umpirsky** [comment]
@zerkms I agree except that it does not solves nothing. It solves slowness on all pages that are not authentication. This is a huge win for me. I agree that it should be investigated further and optimize auth pages.

**Comment by zerkms** [comment]
@umpirsky well, `lazy` does not prevent the service from loading, it just postpones it. My point is that the problem was shifted to other place.

Did you get instant improvement of performance of 26ms everywhere?

**Comment by umpirsky** [comment]
@zerkms No, because it's not used during request that does not trigger 2FA. So it's not instantiated.

**Comment by zerkms** [comment]
@umpirsky have you tried to confirm that with a debugger?

https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/EventListener/RequestListener.php#L84 this line is executed for every request that is not ignored using `excludePattern`.

**Comment by umpirsky** [comment]
@zerkms Yes, that line is executed, but not the `scheb_two_factor.trusted_filter`.

**Comment by zerkms** [comment]
`$this->authHandler` on that line is defined as `<argument type="service" id="scheb_two_factor.trusted_filter" />`

Have you tried to run a debugger and confirm what you say?

**Comment by umpirsky** [comment]
@zerkms You are right, I will check again when I find some time and post results here. Now, I only remember that moving this to lazy fixed the issue for me.

**Comment by zerkms** [comment]
> Now, I only remember that moving this to lazy fixed the issue for me.

It could not have - `lazy` does not reduce the amount of job to be done (it actually increases both cpu and memory footprint in case if the service is used, and it is used in almost every request).

So I believe it is either placebo or some issues with capturing the performance metrics.

**Comment by umpirsky** [comment]
Issue is still here, working on a fix...

**Comment by umpirsky** [comment]
@zerkms https://github.com/scheb/two-factor-bundle/pull/66
