### ISSUE TITLE
Should exclude_pattern check also be in a voter?

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#60]
Currently, even if you specify the `.*` as the `exclude_pattern` you still would get a 403.

It happens because `Scheb\TwoFactorBundle\Security\TwoFactor\Voter` does not take it into account and unconditionally returns `VoterInterface::ACCESS_DENIED` as soon as the session flag is not set.

So the question: is it deliberately that way? If so - what is the typical use case for the `exclude_pattern`?

**Comment by zerkms** [comment]
Does this bundle even need a voter at all? Is not it possible to implement everything in the `kernel.request` event listener?

**Comment by zerkms** [comment]
Yep, and as I see people work it around with https://github.com/scheb/two-factor-bundle/issues/13#issuecomment-206763441

I think the presence of `Voter` should be reconsidered.

**Comment by ReSpawN** [comment]
Lovely. After 2,5 hours of debugging we also stumbled onto the solution and a quick Google confirmed our suggestions via Stackoverflow and minutes later via this Issue. We use it for a dynamic white label page via .CSS, rendered from Twig (as it's dynamic per logged in user). 

Aside from it being in the works as I understand it I really think this should be considered a bug because exclude means exclude on all levels, not 99 out of a 100, as is the case here.

**Comment by scheb** [comment]
The upcoming 3.0 no longer relies on a voter for access management, it's now properly integrated with the security layer. Check out the beta.
