### ISSUE TITLE
Google authentication with FOSUserBundle

### ISSUE THREAD

**Issue by oliverbl4** [scheb/two-factor-bundle#74]
Hi there,

I have installed the bundle in my current project with FOSUserBundle. I added the config, I have disable email and enable google authenticator, and added the in "security" this code:
`access_decision_manager:
        strategy: unanimous`
I don't know why, when I'm trying to get inside the login with my user. The website gives me to the homepage and do not shown me the google authenticator(as if I had not installed the bundle, but I have it).
I can use this command in terminal and gave me the correct code:
`php app/console scheb:two-factor:google-secret`
Please, could you help me with my issue?

**Comment by scheb** [comment]
Does the user entity support Google Authenticator? Does it return a secret from the `getGoogleAuthenticatorSecret()` method?

**Comment by oliverbl4** [comment]
Thanks for the quick reply! :)
This method, return null to me :S

**Comment by scheb** [comment]
Then you need to configure (and return) a GS secret for that user, otherwise the two-factor authentication doesn't know how to generate and validate the authentication code.

**Comment by oliverbl4** [comment]
So basically, I have to generate (and save) a secret code in this column when I log in with my user, no?
I supposed with this method: `$secret = $container->get("scheb_two_factor.security.google_authenticator")->generateSecret();`

**Comment by oliverbl4** [comment]
I need to add some routing?

**Comment by oliverbl4** [comment]
Maybe is because I have this in User?
`class User extends BaseUser implements TwoFactorInterface`

**Comment by scheb** [comment]
Yes, the user needs to have a secret code generated and persisted with the user entity, and let the `getGoogleAuthenticatorSecret()` return that value.

It isn't wise to automatically generate a secret code for users on registration. After registration a user should not have a secret set and and therefore the Google Authenticator would not be active for them. You have to build a page in the account settings where they go to in order to active Google Authenticator for their account. When they choose to active it, you generate a secret code (the command shows you how to generate such a secret code) and persist the code in the user entity. You also show them the code on the page. They can then type that code into their phone (or scan the QR code), to get the acocunt connected to the Google Authenticator app, which generates the two-factor authentication codes.

For debugging it may also be valid to generate a secret code manually with the command and manually edit it in the database.

For more information about the QR code see this issue: Also see: https://github.com/scheb/two-factor-bundle/issues/68

**Comment by oliverbl4** [comment]
I finally fix the problem. The problem solved adding this code in index :)
`$secret = $container->get("scheb_two_factor.security.google_authenticator")->generateSecret();`
Thank you for your quickly support. Great job man, I will recommend this bundle.
