### ISSUE TITLE
Using deprecated event_dispatcher, switch it out

### ISSUE THREAD

**Issue by cordoval** [scheb/two-factor-bundle#87]
The event_dispatcher service uses the Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher class, which has been deprecated in Symfony 3.3. Use the Symfony\Component\EventDispatcher\EventDispatcher class instead.

``` xml
<service id="scheb_two_factor.provider_registry" class="%scheb_two_factor.provider_registry.class%" lazy="true">
			<argument type="service" id="scheb_two_factor.session_flag_manager" />
            <argument type="service" id="event_dispatcher" />
            <argument>%scheb_two_factor.parameter_names.auth_code%</argument>
            <argument /> <!-- Two-factor providers -->
		</service>
```

**Comment by cordoval** [comment]
addressing in https://github.com/scheb/two-factor-bundle/pull/88

**Comment by xabbuh** [comment]
@cordoval I don't see what you want to get changed here. Using the `event_dispatcher` service id not deprecated. You just shouldn't rely on it being an instance of `ContainerAwareEventDispatcher`. Did you run in any deprecation?

**Comment by scheb** [comment]
As already said, the service id `event_dispatcher` is not deprecated, but the class behind that service has been deprecated by the Symfony maintainers, because they intend to replace it with that new class by version 4.0. Until then it will still be the deprecated one to keep backwards compatibility for those people who rely on it being an instance of `ContainerAwareEventDispatcher`. Then, with 4.0 there will be the breaking switch to the new class.

Since the bundle doesn't rely on any of those classes, but only on the `EventDispatcherInterface` we're not having a problem there.

**Comment by cordoval** [comment]
it is an insight.sensiolabs.com problem, thanks for closing the ticket
